app = "pokedex-new"

[env]
  PORT = "5000" 

[processes]
  app = "node app.js"

[deploy]
  strategy = "canary"

[http_service]
  processes = ["app"]
  internal_port = 5000
  min_machines_running = 0
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true

  [[http_service.http_checks]]
    path = "/health"
    protocol = "http"
    method = "GET"
    grace_period = "5s"
    interval = "10s"
    timeout = "2s"